m4_include(`list.m4')
m4_include(`def.m4')
m4_divert(`-1')
m4_define_ifdef(`switch_frontends_header',      `header',       `#include "$1"')
m4_define_ifdef(`switch_tree_header',           `tree_header',  `#include "$1"')
m4_define_ifdef(`switch_frontends_compiler',    `compiler',     `{"$1", "$2", "$3", {m4_list_foreach(i, $4, `"i", ')}, &$5},')
m4_define_ifdef(`switch_frontends_preproc',     `preproc',      `{"$1", "$2", &$3},')
m4_divert(`0')
