m4_include(`list.m4')
m4_include(`def.m4')
m4_divert(`-1')
m4_define_ifdef(`header',       `switch_frontends_header',      `#include "$1"')
m4_define_ifdef(`tree_header',  `switch_tree_header',           `#include "$1"')
m4_define_ifdef(`compiler',     `switch_frontends_compiler',    `{"$1", "$2", "$3", {m4_list_foreach(i, $4, `"i", ')}, &$5},')
m4_define_ifdef(`preproc',      `switch_frontends_preproc',     `{"$1", "$2", &$3},')
m4_divert(`0')
